services:
  beszel:
    image: henrygd/beszel:0.18.2
    container_name: "beszel"
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./beszel_data:/beszel_data
    extra_hosts:
      - "host.docker.internal:host-gateway"
